# name: cosway with shell script

# on: push

# jobs:
#   first_job:
#     runs-on: ubuntu-latest
#     steps:
#     - name: welcome message
#       run: echo "my first github actions job"
    
#     - name: clone the repo
#       uses: actions/checkout@v4

#     - name: list files
#       run: ls

#     - name: executing the cowsay script
#       run: |
#         chmod +x cowsay.sh
#         ./cowsay.sh
    # - name: install cosway
    #   run: sudo apt-get install cowsay -y

    # - name: generate ASCII artwork
    #   run: cowsay -f dargon "Run for cover, I am a dragon ... RARW" >> dragon.txt

    # - name: read file
    #   run: cat dragon.txt

################################################## needs ##################################################
# name: cosway with needs then uplaod and download

# on: push

# jobs:
#   build_job_1:
#     runs-on: ubuntu-latest
#     steps:
#     - name: install cosway
#       run: sudo apt-get install cowsay -y

#     - name: generate ASCII artwork
#       run: cowsay -f dragon "Run for cover, I am a dragon ... RARW" >> dragon.txt

#     - name: read file
#       run: cat dragon.txt

#     - name: upload the dragon.tx file to be downloaded after that from other jobs
#       uses: actions/upload-artifact@v4
#       with:
#         name: dragon-text-file
#         path: dragon.txt

#     - name: sleep for 30 sec
#       run: sleep 30

#   test_job_2:
#     needs: build_job_1
#     runs-on: ubuntu-latest
#     steps:

#     - name: sleep for 30 sec
#       run: sleep 30

#     - name: download  the dragon.tx file to cat it
#       uses: actions/download-artifact@v4
#       with:
#         name: dragon-text-file

#     - name: test file exists
#       run: grep -i "dragon" dragon.txt

#   deploy_job_3:
#     needs: [build_job_1, test_job_2]
#     runs-on: ubuntu-latest
#     steps:
#     - name: download  the dragon.tx file to cat it
#       uses: actions/download-artifact@v4
#       with:
#         name: dragon-text-file

#     - name: read file
#       run: cat dragon.txt


################################################## 03- variables and secres ##################################################

name: Exploring variables and secrets

on: push

env:
    CONTAINER_REGISTERY: docker.io
    IMAGE_NAME: github-actions

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: docker build 
      run:  docker build -t ${{ env.CONTAINER_REGISTERY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    - name: docker login
      # env:
      #   DOCKER_PASSWORD: 
      run:  docker login --username=$${{ vars.DOCKER_USERNAME }} --pasword=${{ secrets.DOCKER_PASSWORD}}

    - name: docker publish
      run:  docker push $CONTAINER_REGISTERY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:

    - name: docker run
      run:  docker run -d -p 8080:80 $CONTAINER_REGISTERY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest