name: cosway with shell script

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: welcome message
      run: echo "my first github actions job"
    
    - name: clone the repo
      uses: actions/checkout@v4

    - name: list files
      run: ls

    - name: executing the cowsay script
      run: |
        chmod o+x cowsay.sh
        ./cowsay.sh
    # - name: install cosway
    #   run: sudo apt-get install cowsay -y

    # - name: generate ASCII artwork
    #   run: cowsay -f dargon "Run for cover, I am a dragon ... RARW" >> dragon.txt

    # - name: read file
    #   run: cat dragon.txt
