# name: cosway with shell script

# on: push

# jobs:
#   first_job:
#     runs-on: ubuntu-latest
#     steps:
#     - name: welcome message
#       run: echo "my first github actions job"
    
#     - name: clone the repo
#       uses: actions/checkout@v4

#     - name: list files
#       run: ls

#     - name: executing the cowsay script
#       run: |
#         chmod +x cowsay.sh
#         ./cowsay.sh
    # - name: install cosway
    #   run: sudo apt-get install cowsay -y

    # - name: generate ASCII artwork
    #   run: cowsay -f dargon "Run for cover, I am a dragon ... RARW" >> dragon.txt

    # - name: read file
    #   run: cat dragon.txt

################################################## needs ##################################################
name: cosway with needs then uplaod and download

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: install cosway
      run: sudo apt-get install cowsay -y

    - name: generate ASCII artwork
      run: cowsay -f dragon "Run for cover, I am a dragon ... RARW" >> dragon.txt

    - name: read file
      run: cat dragon.txt

    - name: upload the dragon.tx file to be downloaded after that from other jobs
      uses: actions/upload-artifact@v3
      with:
        name: dragon-text-file
        path: dragon.txt

    - name: sleep for 30 sec
      run: sleep 30

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:

    - name: sleep for 30 sec
      run: sleep 30

    - name: download  the dragon.tx file to cat it
      uses: actions/download-artifact@v3
      with:
        name: dragon-text-file

    - name: test file exists
      run: grep -i "dragon" dragon.txt

  deploy_job_3:
    needs: [build_job_1, test_job_2]
    runs-on: ubuntu-latest
    steps:
    - name: read file
      run: cat dragon.txt
