name: Exploring variables and secrets

on: push

env:
    CONTAINER_REGISTERY: docker.io
    IMAGE_NAME: github-actions

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: docker build 
      run: echo docker build -t ${{ env.CONTAINER_REGISTERY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME

    - name: docker login
      # env:
      #   DOCKER_PASSWORD: 
      run: echo docker login --username=$${{ vars.DOCKER_USERNAME }} --pasword=${{ secrets.DOCKER_PASSWORD}}

    - name: docker publish
      run: echo docker push $CONTAINER_REGISTERY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:

    - name: docker run
      run: docker run -d -p 8080:80 $CONTAINER_REGISTERY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
